## Pandas import

In [76]:
import  pandas as pd

## Load movie and credit data csv

In [77]:
movie_data = pd.read_csv("../data/movie.csv")
credit_data = pd.read_csv("../data/credit.csv")

In [78]:
combine_data = pd.merge(movie_data,credit_data, on="title")

In [79]:
combine_data.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

### Columns to drop:
### budget, homepage, popularity, release_date, revenue, runtime, spoken_language, original_language, status, vote_average, vote_count, id, movie_id, production_company, production_countries

In [80]:
combine_data = combine_data.drop(["budget", "homepage", "popularity", "release_date", "revenue", "runtime", "spoken_languages", "original_language", "status", "vote_average", "vote_count", "original_title", "keywords", "movie_id", "production_companies", "production_countries", "tagline"], axis=1)

In [81]:
combine_data = combine_data.dropna(subset=["overview"])

In [82]:
combine_data.isnull().sum()

genres      0
id          0
overview    0
title       0
cast        0
crew        0
dtype: int64

In [83]:
import json

In [84]:
def pick_name_genre(obj: str) -> list:
    actual_obj_list = json.loads(obj)

    name_list = []
    for dic in actual_obj_list:
        name_list.append(dic["name"])
    return name_list

def pick_name_cast(obj: str) -> list:
    actual_obj_list = json.loads(obj)

    name_list = []
    count = 0
    for dic in actual_obj_list:
        if count < 3:
            name_list.append(dic["name"])
            count += 1
        else:
            break

    return name_list

def pick_director_crew(obj: str) -> list:
    actual_obj_list = json.loads(obj)

    director_name = []
    for dic in actual_obj_list:
        if dic["job"] == "Director":
            director_name.append(dic["name"])
            break
    return director_name

In [85]:
combine_data["genres"] = combine_data["genres"].apply(pick_name_genre)

In [86]:
combine_data["cast"] = combine_data["cast"].apply(pick_name_cast)

In [87]:
combine_data["crew"] = combine_data["crew"].apply(pick_director_crew)

In [88]:
combine_data["overview"] = combine_data["overview"].apply(lambda x : x.split())

In [89]:
combine_data["tagline"] = combine_data["genres"] + combine_data["overview"] + combine_data["cast"] + combine_data["crew"]

In [90]:
combine_data["tagline"] = combine_data["tagline"].apply(lambda x : [word.lower() for word in x])

In [91]:
combine_data.sample(5)

,genres,id,overview,title,cast,crew,tagline
3950,"[TV Movie, Action, Drama, Family]",22488,"[The, continued, Westward, journey, of, settle...",Love's Abiding Joy,"[Erin Cottrell, Logan Bartholomew, William Mor...",[Michael Landon Jr.],"[tv movie, action, drama, family, the, continu..."
4734,"[Comedy, Horror, Science Fiction]",18841,"[Remember, the, good, old, days, when, anyone,...",The Lost Skeleton of Cadavra,"[Fay Masterson, Andrew Parks, Susan McConnell]",[Larry Blamire],"[comedy, horror, science fiction, remember, th..."
4344,"[Drama, Horror]",11298,"[After, a, bizarre, and, near, fatal, encounte...",The Howling,"[Patrick Macnee, Dennis Dugan, Christopher Stone]",[Joe Dante],"[drama, horror, after, a, bizarre, and, near, ..."
1235,"[Crime, Action, Adventure]",11398,"[When, ruthless, terrorists, threaten, to, bri...",The Art of War,"[Wesley Snipes, Donald Sutherland, Maury Chaykin]",[Christian Duguay],"[crime, action, adventure, when, ruthless, ter..."
2678,"[Horror, Thriller]",9877,"[There's, a, campus, killer, on, the, loose, w...",Urban Legend,"[Alicia Witt, Jared Leto, Rebecca Gayheart]",[Jamie Blanks],"[horror, thriller, there's, a, campus, killer,..."

In [92]:
final_data = combine_data.drop(["genres", "overview", "crew", "cast"], axis=1)

In [93]:
final_data["tagline"] = final_data["tagline"].apply(lambda x: " ".join(x))

In [94]:
final_data.head()

,id,title,tagline
0,19995,Avatar,action adventure fantasy science fiction in th...
1,285,Pirates of the Caribbean: At World's End,"adventure fantasy action captain barbossa, lon..."
2,206647,Spectre,action adventure crime a cryptic message from ...
3,49026,The Dark Knight Rises,action crime drama thriller following the deat...
4,49529,John Carter,action adventure science fiction john carter i...

## Final data is safe in file data/final_data.csv

In [95]:
final_data["title"].duplicated().sum()

np.int64(9)

In [96]:
final_data.drop_duplicates(subset=["title"], inplace=True)

In [97]:
final_data["title"].duplicated().sum()

np.int64(0)

In [98]:
final_data.to_csv("../data/final_data.csv", index=False)